name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        cd src 
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd src 
        dotnet test --collect:"XPlat Code Coverage" --no-restore --verbosity normal
    - name: Codecov
      uses: codecov/codecov-action@v1.0.12
      with:
         token: ${{ secrets.CODECOV_TOKEN }}
         file: /**/coverage.cobertura.xml

